/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * API version: 1.5.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// SMS message object
type Message struct {
	// The sender of the message. Should be no longer than 11 characters for alphanumeric or 15 characters for numeric sender ID's. No spaces or special characters.
	Sender string `json:"sender"`
	// Telephone number of the recipient
	Destination string `json:"destination"`
	// Message to send to the recipient. Content can be up to 1280 characters in length. Messages of 160 characters or fewer are charged 1 credit. If your message is longer than 160 characters then it will be broken down in to chunks of 153 characters before being sent to the recipient's handset, and you will be charged 1 credit for each 153 characters. Messages sent to numbers registered outside the UK will be typically charged double credits, but for certain countries may be charged fractions of credits (e.g. 2.5). Please contact us for rates for each country.
	Content string `json:"content"`
	// The url to which we should POST delivery reports to for this message. If none is specified, we'll use the global delivery report URL that you've configured on your account page.
	Deliveryreporturl string `json:"deliveryreporturl,omitempty"`
	// Date at which to send the message. This is only used by the message/schedule service and can be left empty for other services.
	Schedule string `json:"schedule,omitempty"`
	// An identifying label for the message, which you can use to filter and report on messages you've sent later. Ideal for campaigns. A maximum of 280 characters.
	Tag string `json:"tag,omitempty"`
	// The optional number of minutes before the message is deleted. Optional. Omit to prevent delivery report deletion. Integer.
	Ttl float64 `json:"ttl,omitempty"`
	// An optional list of email addresses to forward responses to this specific message to. An SMS Works Reply Number is required to use this feature.
	Responseemail []string `json:"responseemail,omitempty"`
	Metadata *MessageMetadata `json:"metadata,omitempty"`
}
