/*
The SMS Works API

The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.

API version: 1.9.0
Contact: support@thesmsworks.co.uk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the CreditsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreditsResponse{}

// CreditsResponse struct for CreditsResponse
type CreditsResponse struct {
	// The number of remaining credits on your SMS Works account. Floating point number.
	Credits float32 `json:"credits"`
}

type _CreditsResponse CreditsResponse

// NewCreditsResponse instantiates a new CreditsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreditsResponse(credits float32) *CreditsResponse {
	this := CreditsResponse{}
	this.Credits = credits
	return &this
}

// NewCreditsResponseWithDefaults instantiates a new CreditsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreditsResponseWithDefaults() *CreditsResponse {
	this := CreditsResponse{}
	return &this
}

// GetCredits returns the Credits field value
func (o *CreditsResponse) GetCredits() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Credits
}

// GetCreditsOk returns a tuple with the Credits field value
// and a boolean to check if the value has been set.
func (o *CreditsResponse) GetCreditsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Credits, true
}

// SetCredits sets field value
func (o *CreditsResponse) SetCredits(v float32) {
	o.Credits = v
}

func (o CreditsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreditsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["credits"] = o.Credits
	return toSerialize, nil
}

func (o *CreditsResponse) UnmarshalJSON(bytes []byte) (err error) {
    // This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"credits",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreditsResponse := _CreditsResponse{}

	err = json.Unmarshal(bytes, &varCreditsResponse)

	if err != nil {
		return err
	}

	*o = CreditsResponse(varCreditsResponse)

	return err
}

type NullableCreditsResponse struct {
	value *CreditsResponse
	isSet bool
}

func (v NullableCreditsResponse) Get() *CreditsResponse {
	return v.value
}

func (v *NullableCreditsResponse) Set(val *CreditsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreditsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreditsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreditsResponse(val *CreditsResponse) *NullableCreditsResponse {
	return &NullableCreditsResponse{value: val, isSet: true}
}

func (v NullableCreditsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreditsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


