/*
The SMS Works API

The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.

API version: 1.9.0
Contact: support@thesmsworks.co.uk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the BatchMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchMessage{}

// BatchMessage SMS Message Batch
type BatchMessage struct {
	// The sender of the message. Should be no longer than 11 characters for alphanumeric or 15 characters for numeric sender ID's. No spaces or special characters.
	Sender string `json:"sender"`
	// Telephone numbers of each of the recipients
	Destinations []string `json:"destinations"`
	// Message to send to the recipient
	Content string `json:"content"`
	// The url to which we should POST delivery reports to for this message. If none is specified, we'll use the global delivery report URL that you've configured on your account page.
	Deliveryreporturl *string `json:"deliveryreporturl,omitempty"`
	// Date-time at which to send the batch. This is only used by the batch/schedule service.
	Schedule *string `json:"schedule,omitempty"`
	// An identifying label for the message, which you can use to filter and report on messages you've sent later. Ideal for campaigns. A maximum of 280 characters.
	Tag *string `json:"tag,omitempty"`
	// The number of minutes before the delivery report is deleted. Optional. Omit to prevent delivery report deletion. Integer.
	Ttl *float32 `json:"ttl,omitempty"`
	// The optional number of minutes to attempt delivery before the message is marked as EXPIRED. Optional. The default is 2880 minutes. Integer.
	Validity *float32 `json:"validity,omitempty"`
	// Used to determine whether The SMS Works AI Optimiser should be used in the event that the message is just longer than the 1 or 2 credit boundary. This setting overrides the AI Optimiser configuration on your SMS Works account.
	Ai *bool `json:"ai,omitempty"`
}

type _BatchMessage BatchMessage

// NewBatchMessage instantiates a new BatchMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchMessage(sender string, destinations []string, content string) *BatchMessage {
	this := BatchMessage{}
	this.Sender = sender
	this.Destinations = destinations
	this.Content = content
	return &this
}

// NewBatchMessageWithDefaults instantiates a new BatchMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchMessageWithDefaults() *BatchMessage {
	this := BatchMessage{}
	return &this
}

// GetSender returns the Sender field value
func (o *BatchMessage) GetSender() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sender
}

// GetSenderOk returns a tuple with the Sender field value
// and a boolean to check if the value has been set.
func (o *BatchMessage) GetSenderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sender, true
}

// SetSender sets field value
func (o *BatchMessage) SetSender(v string) {
	o.Sender = v
}

// GetDestinations returns the Destinations field value
func (o *BatchMessage) GetDestinations() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Destinations
}

// GetDestinationsOk returns a tuple with the Destinations field value
// and a boolean to check if the value has been set.
func (o *BatchMessage) GetDestinationsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Destinations, true
}

// SetDestinations sets field value
func (o *BatchMessage) SetDestinations(v []string) {
	o.Destinations = v
}

// GetContent returns the Content field value
func (o *BatchMessage) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *BatchMessage) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *BatchMessage) SetContent(v string) {
	o.Content = v
}

// GetDeliveryreporturl returns the Deliveryreporturl field value if set, zero value otherwise.
func (o *BatchMessage) GetDeliveryreporturl() string {
	if o == nil || IsNil(o.Deliveryreporturl) {
		var ret string
		return ret
	}
	return *o.Deliveryreporturl
}

// GetDeliveryreporturlOk returns a tuple with the Deliveryreporturl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchMessage) GetDeliveryreporturlOk() (*string, bool) {
	if o == nil || IsNil(o.Deliveryreporturl) {
		return nil, false
	}
	return o.Deliveryreporturl, true
}

// HasDeliveryreporturl returns a boolean if a field has been set.
func (o *BatchMessage) HasDeliveryreporturl() bool {
	if o != nil && !IsNil(o.Deliveryreporturl) {
		return true
	}

	return false
}

// SetDeliveryreporturl gets a reference to the given string and assigns it to the Deliveryreporturl field.
func (o *BatchMessage) SetDeliveryreporturl(v string) {
	o.Deliveryreporturl = &v
}

// GetSchedule returns the Schedule field value if set, zero value otherwise.
func (o *BatchMessage) GetSchedule() string {
	if o == nil || IsNil(o.Schedule) {
		var ret string
		return ret
	}
	return *o.Schedule
}

// GetScheduleOk returns a tuple with the Schedule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchMessage) GetScheduleOk() (*string, bool) {
	if o == nil || IsNil(o.Schedule) {
		return nil, false
	}
	return o.Schedule, true
}

// HasSchedule returns a boolean if a field has been set.
func (o *BatchMessage) HasSchedule() bool {
	if o != nil && !IsNil(o.Schedule) {
		return true
	}

	return false
}

// SetSchedule gets a reference to the given string and assigns it to the Schedule field.
func (o *BatchMessage) SetSchedule(v string) {
	o.Schedule = &v
}

// GetTag returns the Tag field value if set, zero value otherwise.
func (o *BatchMessage) GetTag() string {
	if o == nil || IsNil(o.Tag) {
		var ret string
		return ret
	}
	return *o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchMessage) GetTagOk() (*string, bool) {
	if o == nil || IsNil(o.Tag) {
		return nil, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *BatchMessage) HasTag() bool {
	if o != nil && !IsNil(o.Tag) {
		return true
	}

	return false
}

// SetTag gets a reference to the given string and assigns it to the Tag field.
func (o *BatchMessage) SetTag(v string) {
	o.Tag = &v
}

// GetTtl returns the Ttl field value if set, zero value otherwise.
func (o *BatchMessage) GetTtl() float32 {
	if o == nil || IsNil(o.Ttl) {
		var ret float32
		return ret
	}
	return *o.Ttl
}

// GetTtlOk returns a tuple with the Ttl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchMessage) GetTtlOk() (*float32, bool) {
	if o == nil || IsNil(o.Ttl) {
		return nil, false
	}
	return o.Ttl, true
}

// HasTtl returns a boolean if a field has been set.
func (o *BatchMessage) HasTtl() bool {
	if o != nil && !IsNil(o.Ttl) {
		return true
	}

	return false
}

// SetTtl gets a reference to the given float32 and assigns it to the Ttl field.
func (o *BatchMessage) SetTtl(v float32) {
	o.Ttl = &v
}

// GetValidity returns the Validity field value if set, zero value otherwise.
func (o *BatchMessage) GetValidity() float32 {
	if o == nil || IsNil(o.Validity) {
		var ret float32
		return ret
	}
	return *o.Validity
}

// GetValidityOk returns a tuple with the Validity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchMessage) GetValidityOk() (*float32, bool) {
	if o == nil || IsNil(o.Validity) {
		return nil, false
	}
	return o.Validity, true
}

// HasValidity returns a boolean if a field has been set.
func (o *BatchMessage) HasValidity() bool {
	if o != nil && !IsNil(o.Validity) {
		return true
	}

	return false
}

// SetValidity gets a reference to the given float32 and assigns it to the Validity field.
func (o *BatchMessage) SetValidity(v float32) {
	o.Validity = &v
}

// GetAi returns the Ai field value if set, zero value otherwise.
func (o *BatchMessage) GetAi() bool {
	if o == nil || IsNil(o.Ai) {
		var ret bool
		return ret
	}
	return *o.Ai
}

// GetAiOk returns a tuple with the Ai field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BatchMessage) GetAiOk() (*bool, bool) {
	if o == nil || IsNil(o.Ai) {
		return nil, false
	}
	return o.Ai, true
}

// HasAi returns a boolean if a field has been set.
func (o *BatchMessage) HasAi() bool {
	if o != nil && !IsNil(o.Ai) {
		return true
	}

	return false
}

// SetAi gets a reference to the given bool and assigns it to the Ai field.
func (o *BatchMessage) SetAi(v bool) {
	o.Ai = &v
}

func (o BatchMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sender"] = o.Sender
	toSerialize["destinations"] = o.Destinations
	toSerialize["content"] = o.Content
	if !IsNil(o.Deliveryreporturl) {
		toSerialize["deliveryreporturl"] = o.Deliveryreporturl
	}
	if !IsNil(o.Schedule) {
		toSerialize["schedule"] = o.Schedule
	}
	if !IsNil(o.Tag) {
		toSerialize["tag"] = o.Tag
	}
	if !IsNil(o.Ttl) {
		toSerialize["ttl"] = o.Ttl
	}
	if !IsNil(o.Validity) {
		toSerialize["validity"] = o.Validity
	}
	if !IsNil(o.Ai) {
		toSerialize["ai"] = o.Ai
	}
	return toSerialize, nil
}

func (o *BatchMessage) UnmarshalJSON(bytes []byte) (err error) {
    // This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sender",
		"destinations",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchMessage := _BatchMessage{}

	err = json.Unmarshal(bytes, &varBatchMessage)

	if err != nil {
		return err
	}

	*o = BatchMessage(varBatchMessage)

	return err
}

type NullableBatchMessage struct {
	value *BatchMessage
	isSet bool
}

func (v NullableBatchMessage) Get() *BatchMessage {
	return v.value
}

func (v *NullableBatchMessage) Set(val *BatchMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchMessage(val *BatchMessage) *NullableBatchMessage {
	return &NullableBatchMessage{value: val, isSet: true}
}

func (v NullableBatchMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


