/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * API version: 1.5.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ExtendedErrorModel struct {
	Message string `json:"message"`
	// Numeric code used to identify the error. Integer.
	ErrorCode float64 `json:"errorCode"`
	Status string `json:"status"`
	Permanent bool `json:"permanent,omitempty"`
}
