/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * API version: 1.5.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MessageResponse struct {
	Batchid string `json:"batchid,omitempty"`
	Content string `json:"content"`
	Created string `json:"created"`
	Customerid string `json:"customerid"`
	Deliveryreporturl string `json:"deliveryreporturl,omitempty"`
	Destination float64 `json:"destination"`
	Failurereason *MessageResponseFailurereason `json:"failurereason,omitempty"`
	Id string `json:"id,omitempty"`
	Identifier string `json:"identifier,omitempty"`
	Keyword string `json:"keyword,omitempty"`
	Messageid string `json:"messageid"`
	Modified string `json:"modified"`
	Schedule string `json:"schedule"`
	Status string `json:"status"`
	Sender string `json:"sender"`
	Tag string `json:"tag"`
}
