/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * API version: 1.5.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Key/value pair that will be returned to you in the API call response.
type MetaData struct {
	// key of the key/value pair
	Key string `json:"key,omitempty"`
	// value of the key/value pair
	Value string `json:"value,omitempty"`
}
