/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * API version: 1.5.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// authorisation object
type Login struct {
	// Your customer ID, available from your account area at https://thesmsworks.co.uk/user/login
	Customerid string `json:"customerid,omitempty"`
	// API Key, available from your account area at https://thesmsworks.co.uk/user/login
	Key string `json:"key,omitempty"`
	// API Secret, available from your account area at https://thesmsworks.co.uk/user/login
	Secret string `json:"secret,omitempty"`
}
