/*
The SMS Works API

The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.

API version: 1.9.0
Contact: support@thesmsworks.co.uk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the SendMessageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendMessageResponse{}

// SendMessageResponse struct for SendMessageResponse
type SendMessageResponse struct {
	Messageid string `json:"messageid"`
	Status string `json:"status"`
	// The number of remaining credits on your SMS Works account. Floating point number.
	Credits float32 `json:"credits"`
	// The number of credits used to send the message. Floating point number.
	CreditsUsed float32 `json:"creditsUsed"`
}

type _SendMessageResponse SendMessageResponse

// NewSendMessageResponse instantiates a new SendMessageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendMessageResponse(messageid string, status string, credits float32, creditsUsed float32) *SendMessageResponse {
	this := SendMessageResponse{}
	this.Messageid = messageid
	this.Status = status
	this.Credits = credits
	this.CreditsUsed = creditsUsed
	return &this
}

// NewSendMessageResponseWithDefaults instantiates a new SendMessageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendMessageResponseWithDefaults() *SendMessageResponse {
	this := SendMessageResponse{}
	return &this
}

// GetMessageid returns the Messageid field value
func (o *SendMessageResponse) GetMessageid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Messageid
}

// GetMessageidOk returns a tuple with the Messageid field value
// and a boolean to check if the value has been set.
func (o *SendMessageResponse) GetMessageidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Messageid, true
}

// SetMessageid sets field value
func (o *SendMessageResponse) SetMessageid(v string) {
	o.Messageid = v
}

// GetStatus returns the Status field value
func (o *SendMessageResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *SendMessageResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *SendMessageResponse) SetStatus(v string) {
	o.Status = v
}

// GetCredits returns the Credits field value
func (o *SendMessageResponse) GetCredits() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Credits
}

// GetCreditsOk returns a tuple with the Credits field value
// and a boolean to check if the value has been set.
func (o *SendMessageResponse) GetCreditsOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Credits, true
}

// SetCredits sets field value
func (o *SendMessageResponse) SetCredits(v float32) {
	o.Credits = v
}

// GetCreditsUsed returns the CreditsUsed field value
func (o *SendMessageResponse) GetCreditsUsed() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CreditsUsed
}

// GetCreditsUsedOk returns a tuple with the CreditsUsed field value
// and a boolean to check if the value has been set.
func (o *SendMessageResponse) GetCreditsUsedOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreditsUsed, true
}

// SetCreditsUsed sets field value
func (o *SendMessageResponse) SetCreditsUsed(v float32) {
	o.CreditsUsed = v
}

func (o SendMessageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendMessageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["messageid"] = o.Messageid
	toSerialize["status"] = o.Status
	toSerialize["credits"] = o.Credits
	toSerialize["creditsUsed"] = o.CreditsUsed
	return toSerialize, nil
}

func (o *SendMessageResponse) UnmarshalJSON(bytes []byte) (err error) {
    // This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"messageid",
		"status",
		"credits",
		"creditsUsed",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSendMessageResponse := _SendMessageResponse{}

	err = json.Unmarshal(bytes, &varSendMessageResponse)

	if err != nil {
		return err
	}

	*o = SendMessageResponse(varSendMessageResponse)

	return err
}

type NullableSendMessageResponse struct {
	value *SendMessageResponse
	isSet bool
}

func (v NullableSendMessageResponse) Get() *SendMessageResponse {
	return v.value
}

func (v *NullableSendMessageResponse) Set(val *SendMessageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSendMessageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSendMessageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendMessageResponse(val *SendMessageResponse) *NullableSendMessageResponse {
	return &NullableSendMessageResponse{value: val, isSet: true}
}

func (v NullableSendMessageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendMessageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


