/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * API version: 1.5.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MessageResponseFailurereason struct {
	// Numeric code that defines the error. Integer.
	Code float64 `json:"code,omitempty"`
	Details string `json:"details,omitempty"`
	Permanent bool `json:"permanent,omitempty"`
}
