/*
The SMS Works API

The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.

API version: 1.9.0
Contact: support@thesmsworks.co.uk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the DeletedMessageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeletedMessageResponse{}

// DeletedMessageResponse struct for DeletedMessageResponse
type DeletedMessageResponse struct {
	Messageid string `json:"messageid"`
	Status string `json:"status"`
}

type _DeletedMessageResponse DeletedMessageResponse

// NewDeletedMessageResponse instantiates a new DeletedMessageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeletedMessageResponse(messageid string, status string) *DeletedMessageResponse {
	this := DeletedMessageResponse{}
	this.Messageid = messageid
	this.Status = status
	return &this
}

// NewDeletedMessageResponseWithDefaults instantiates a new DeletedMessageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeletedMessageResponseWithDefaults() *DeletedMessageResponse {
	this := DeletedMessageResponse{}
	return &this
}

// GetMessageid returns the Messageid field value
func (o *DeletedMessageResponse) GetMessageid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Messageid
}

// GetMessageidOk returns a tuple with the Messageid field value
// and a boolean to check if the value has been set.
func (o *DeletedMessageResponse) GetMessageidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Messageid, true
}

// SetMessageid sets field value
func (o *DeletedMessageResponse) SetMessageid(v string) {
	o.Messageid = v
}

// GetStatus returns the Status field value
func (o *DeletedMessageResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *DeletedMessageResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *DeletedMessageResponse) SetStatus(v string) {
	o.Status = v
}

func (o DeletedMessageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeletedMessageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["messageid"] = o.Messageid
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *DeletedMessageResponse) UnmarshalJSON(bytes []byte) (err error) {
    // This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"messageid",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeletedMessageResponse := _DeletedMessageResponse{}

	err = json.Unmarshal(bytes, &varDeletedMessageResponse)

	if err != nil {
		return err
	}

	*o = DeletedMessageResponse(varDeletedMessageResponse)

	return err
}

type NullableDeletedMessageResponse struct {
	value *DeletedMessageResponse
	isSet bool
}

func (v NullableDeletedMessageResponse) Get() *DeletedMessageResponse {
	return v.value
}

func (v *NullableDeletedMessageResponse) Set(val *DeletedMessageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeletedMessageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeletedMessageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeletedMessageResponse(val *DeletedMessageResponse) *NullableDeletedMessageResponse {
	return &NullableDeletedMessageResponse{value: val, isSet: true}
}

func (v NullableDeletedMessageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeletedMessageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


