/*
The SMS Works API

The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.

API version: 1.9.0
Contact: support@thesmsworks.co.uk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ScheduledMessagesResponseMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScheduledMessagesResponseMessage{}

// ScheduledMessagesResponseMessage struct for ScheduledMessagesResponseMessage
type ScheduledMessagesResponseMessage struct {
	Schema *ScheduledMessage `json:"schema,omitempty"`
}

// NewScheduledMessagesResponseMessage instantiates a new ScheduledMessagesResponseMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScheduledMessagesResponseMessage() *ScheduledMessagesResponseMessage {
	this := ScheduledMessagesResponseMessage{}
	return &this
}

// NewScheduledMessagesResponseMessageWithDefaults instantiates a new ScheduledMessagesResponseMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScheduledMessagesResponseMessageWithDefaults() *ScheduledMessagesResponseMessage {
	this := ScheduledMessagesResponseMessage{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *ScheduledMessagesResponseMessage) GetSchema() ScheduledMessage {
	if o == nil || IsNil(o.Schema) {
		var ret ScheduledMessage
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ScheduledMessagesResponseMessage) GetSchemaOk() (*ScheduledMessage, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *ScheduledMessagesResponseMessage) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given ScheduledMessage and assigns it to the Schema field.
func (o *ScheduledMessagesResponseMessage) SetSchema(v ScheduledMessage) {
	o.Schema = &v
}

func (o ScheduledMessagesResponseMessage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScheduledMessagesResponseMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["schema"] = o.Schema
	}
	return toSerialize, nil
}

type NullableScheduledMessagesResponseMessage struct {
	value *ScheduledMessagesResponseMessage
	isSet bool
}

func (v NullableScheduledMessagesResponseMessage) Get() *ScheduledMessagesResponseMessage {
	return v.value
}

func (v *NullableScheduledMessagesResponseMessage) Set(val *ScheduledMessagesResponseMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableScheduledMessagesResponseMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableScheduledMessagesResponseMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScheduledMessagesResponseMessage(val *ScheduledMessagesResponseMessage) *NullableScheduledMessagesResponseMessage {
	return &NullableScheduledMessagesResponseMessage{value: val, isSet: true}
}

func (v NullableScheduledMessagesResponseMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScheduledMessagesResponseMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


