/*
 * The SMS Works API
 *
 * The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed messages are refunded.
 *
 * API version: 1.5.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SendMessageResponse struct {
	Messageid string `json:"messageid"`
	Status string `json:"status"`
	// The number of remaining credits on your SMS Works account. Floating point number.
	Credits float64 `json:"credits"`
	// The number of credits used to send the message. Floating point number.
	CreditsUsed float64 `json:"creditsUsed"`
}
