/*
The SMS Works API

The SMS Works provides a low-cost, reliable SMS API for developers. Pay only for delivered texts, all failed UK messages are refunded.

API version: 1.9.0
Contact: support@thesmsworks.co.uk
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the QueryMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryMetadata{}

// QueryMetadata An array of objects containing metadata key/value pairs that have been saved on messages.
type QueryMetadata struct {
	Schema *MetaData `json:"schema,omitempty"`
}

// NewQueryMetadata instantiates a new QueryMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryMetadata() *QueryMetadata {
	this := QueryMetadata{}
	return &this
}

// NewQueryMetadataWithDefaults instantiates a new QueryMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryMetadataWithDefaults() *QueryMetadata {
	this := QueryMetadata{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *QueryMetadata) GetSchema() MetaData {
	if o == nil || IsNil(o.Schema) {
		var ret MetaData
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QueryMetadata) GetSchemaOk() (*MetaData, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *QueryMetadata) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given MetaData and assigns it to the Schema field.
func (o *QueryMetadata) SetSchema(v MetaData) {
	o.Schema = &v
}

func (o QueryMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["schema"] = o.Schema
	}
	return toSerialize, nil
}

type NullableQueryMetadata struct {
	value *QueryMetadata
	isSet bool
}

func (v NullableQueryMetadata) Get() *QueryMetadata {
	return v.value
}

func (v *NullableQueryMetadata) Set(val *QueryMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryMetadata(val *QueryMetadata) *NullableQueryMetadata {
	return &NullableQueryMetadata{value: val, isSet: true}
}

func (v NullableQueryMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


